#!/bin/bash
docker run --detach \
       --publish 50000:50000 \
       --name fuota-server \
       --env US_AUTH_USERNAME=server_username \
       --env US_AUTH_PASSWORD=server_password \
       --env US_SERVER_PORT=50000 \
       --volume fuota-server-volume:/usr/src/data \
       --restart always \
       fuota-server
       
